Problem 1: Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 2 arrays, each with 6 elements:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#code here
arr2D = arr.reshape(2, 6) #reshape function from NumPy library to convert the 1-D array into a 2-D array with 2x6

print(arr2D)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Problem 2: Convert the following 1-D array into a 3d Array with 1 X 3 elements

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#code here
arr3D = arr.reshape(4, 1, 3)

print(arr3D)

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]


Problem 3: Iterate on the elements of the following 3-D array and add 12 if the number is odd and substract -12 if the number is even and print it.


In [3]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#code here
for i in range(arr.shape[0]): ## Iterate elements
    for j in range(arr.shape[1]):
        for k in range(arr.shape[2]):
            if arr[i, j, k] % 2 == 0:
                arr[i, j, k] -= 12
            else:
                arr[i, j, k] += 12
print(arr)

[[[ 13 -10  15]
  [ -8  17  -6]]

 [[ 19  -4  21]
  [ -2  23   0]]]


Problem 4 : Join two 2-D arrays along rows (axis=1):

In [4]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])

#code here
print(np.concatenate((arr1, arr2), axis=1)) #used concatenate function to join the two array

[[  1   2   5   6]
 [  3   4   7   8]
 [  5   6  70  80]
 [  7   8  90 100]
 [  9  10 110 120]]


Problem 5 : Stack two 2-D Array along columns

In [6]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])
#code here
print(np.hstack((arr1, arr2))) #used hstack function to stack the two arrays along columns

[[  1   2   5   6]
 [  3   4   7   8]
 [  5   6  70  80]
 [  7   8  90 100]
 [  9  10 110 120]]


Problem 5 : Stack two 2-D Array along depth

In [7]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])
#code here
print(np.dstack((arr1, arr2))) #used dstack function to stack the two arrays along depth axis

[[[  1   5]
  [  2   6]]

 [[  3   7]
  [  4   8]]

 [[  5  70]
  [  6  80]]

 [[  7  90]
  [  8 100]]

 [[  9 110]
  [ 10 120]]]


Problem 6 : Create a filter array for the 1d array. If the number is even then store True in then filter array else False
And then filter the initial array using the filter array.

In [8]:

import numpy as np

arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#code here
filter_arr = []

for element in arr: # iterate each element in arr
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

arr2 = arr[filter_arr]

print(filter_arr)
print(arr2)


[False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True]
[42 44 46 48 50  2  4  6  8 10]


Problem 7 : Generate 50 random numbers and store it in numpy array and then apply the same operations in problem 6

In [10]:
from numpy import random

#code here
random_numbers = random.randint(1, 100, 50) # generate 50 random numbers from 1-100
print(random_numbers)

filter_arr2 = []

for element in random_numbers: # iterate each element in random_numbers
  if element % 2 == 0:
    filter_arr2.append(True)
  else:
    filter_arr2.append(False)

final_arr = random_numbers[filter_arr2]

print(filter_arr2)
print(final_arr)

[21 46 35 32 41 75 87 69 20 57 52 86 38 29 25 35 96  8 32 35 59 56 96 85
 51 39 27 46 39 47 15 73  9 49 29 62 44  1 66 56 57 29 60 73 86 33 11 15
 96 56]
[False, True, False, True, False, False, False, False, True, False, True, True, True, False, False, False, True, True, True, False, False, True, True, False, False, False, False, True, False, False, False, False, False, False, False, True, True, False, True, True, False, False, True, False, True, False, False, False, True, True]
[46 32 20 52 86 38 96  8 32 56 96 46 62 44 66 56 60 86 96 56]


Problem 8 :  Slice from the index 3 from the end to index 1 from the end


In [11]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

#code here
print(arr1[-3:-1])

[[5 6]
 [7 8]]


Problem 9 : Return every two other element from index 1 to index 5:

In [13]:
import numpy as np
arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[1:6:2])

[42 44 46]


Problem 10 : Generate a random permutation of elements of following array

In [14]:
import numpy as np
arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#code here
random_permutation_arr = np.random.permutation(arr)

print(random_permutation_arr)

[ 1 49 47 10  5  2  7 43 45 50 42  4 48 41 44  8  6 46  9  3]
